logsBucket: "gs://logs-build-gcpdevops-khalil"

steps:                                                                    # permet de lister les étapes a réaliser
- name: 'gcr.io/cloud-builders/docker'                                    # L’image Docker de Google contenant la commande docker.
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops', '.']              # args : Les arguments passés à la commande docker build
 
 # donc je luis dit : Exécute la commande Docker suivante : docker build -t gcr.io/$PROJECT_ID/gcpdevops .”

- name: 'gcr.io/cloud-builders/docker'
  args: ["push","gcr.io/$PROJECT_ID/gcpdevops"]

#Elle sert à indiquer à Cloud Build quelle(s) image(s) Docker tu veux stocker automatiquement après le build,
# dans le Container Registry ou Artifact Registry de ton projet GCP.

# déployer l'image conteneur dans GKE

- name: "gcr.io/gke-release/gke-deploy"    # l'objet gke-deploy : c'est un objet de google qui permet de déployer automatiquement l'image sur le cluster  
  args: 
  - run
  - -filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/gcpdevops
  - --location=us-centrale1-c
  - --cluster=gcp-devops-project
  - --namespace=gcp-devops-prod