apiVersion: "v1"
kind: Service
metadata:
  name: "gcp-devops-gke-service"
  namespace: gcp-devops-projet
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
  selector:
    app: "gcp"
  type: "LoadBalancer"  # or clusterIp ou nodePort loadBlancer permet d'exposer sur internet 